package com.java.ppp.pppbackend.entity;

public enum NotificationType {
    CONTENT_PUBLISHED,
    CONTENT_APPROVED,
    CONTENT_REJECTED,
    CONTENT_COMMENTED,
    CONTENT_LIKED,
    CONTENT_SHARED,
    MENTION,
    WORKFLOW_ASSIGNED,
    WORKFLOW_APPROVED,
    WORKFLOW_REJECTED,
    SYSTEM_ALERT,
    USER_MESSAGE,
    PASSWORD_RESET,
    EMAIL_VERIFICATION,
    ACCOUNT_UPDATE
}